### ISSUE TITLE
fix tooltip flicker

### ISSUE THREAD

**Issue by glasheen99** [pseudoankit/coachmark#12]
Tooltips flicker, or jump out of position very briefly, in two cases that I've seen:

1. First displayed tooltip.  This seems to go away when tooltips are displayed again.
2. Unpredictably on tooltips other than the first, especially when a new tooltip requires recomposition.  Unlike the first case, this doesn't go away when tooltips are displayed again.

**Comment by glasheen99** [comment]
PR #13

**Comment by ankitk77** [comment]
release in v1.0.4
